app/inside/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField,PasswordField
from wtforms.validators import DataRequired, Length, NumberRange


class KlientiForm(FlaskForm):
    first_name = StringField("Jméno", validators=[DataRequired(), Length(min=2, max=50)],render_kw=dict(class_ = "form-control", placeholder="Zadejte celé jméno klienta (min. 2 znaky)"))
    last_name = StringField("Příjmení", validators=[DataRequired(), Length(min=2, max=50)], render_kw=dict(class_ = "form-control", placeholder="Zadejte příjmení klienta (min. 2 znaky)"))
    email = StringField("Email", validators=[DataRequired(), Length(min=6, max=50)], render_kw=dict(class_ = "form-control", placeholder="Zadejte platný email klienta (min. 6 znaků)"))
    phone_number = StringField("Telefonní číslo", validators=[DataRequired(), Length(min=9, max=15)], render_kw=dict(class_ = "form-control", placeholder="Formát 00420-123456789"))
    birth_year = IntegerField("Rok narození", validators=[DataRequired(), NumberRange(min=1922, max=2022)], render_kw=dict(class_ = "form-control", placeholder="Zadejte rok narození klienta (max. 2022)"))
    street = StringField("Ulice", validators=[DataRequired(), Length(min=2, max=50)], render_kw=dict(class_ = "form-control", placeholder="Zadejte ulici (min. 2 znaky)"))
    city = StringField("Město", validators=[DataRequired(), Length(min=2, max=50)], render_kw=dict(class_ = "form-control", placeholder="Zadejte město (min. 2 znaky)"))
    postal_code = StringField("PSČ", validators=[DataRequired(), Length(min=5, max=6)], render_kw=dict(class_ = "form-control", placeholder="Zadejte PSČ (5 až 6 znaků)"))
    submit = SubmitField("Potvrdit", render_kw=dict(class_="btn btn-primary"))


class PojisteniForm(FlaskForm):
    druh = StringField("Druh", validators=[DataRequired(), Length(min=2, max=50)], render_kw=dict(class_="form-control", placeholder="Zadejte druh pojistení (min. 2 znaky)"))
    pojistovna = StringField("Pojišťovna", validators=[DataRequired(), Length(min=2, max=50)], render_kw=dict(class_="form-control", placeholder="Zadejte název pojišťovny (min. 2 znaky)"))
    pojistna_castka = IntegerField("Pojištná částka", validators=[DataRequired(), NumberRange(min=1000, max=1000000)], render_kw=dict(class_="form-control", placeholder="Zadejte pojištnou částku (1000 až 1000000)"))
    submit = SubmitField("Potvrdit", render_kw=dict(class_="btn btn-primary"))

app/inside/__init__.py
from flask import Blueprint

inside_bp = Blueprint("inside_bp", __name__, template_folder="templates")

app/inside/views.py
from flask import render_template, flash, redirect, url_for, get_flashed_messages
from app.inside import inside_bp
from app.inside.forms import KlientiForm, PojisteniForm
from app import db
from app.models import Klienti, Pojisteni
from flask_login import current_user, login_required
from app.models import Uzivatele
from app.inside.utils import (
    add_client,
    add_policy,
    views,
    soucet_klientu,
    soucet_pojisteni,
    klient_s_pojistenim,
    pojistka_bez_klienta,
   # klienti_bez_pojisteni,
    pojistka_s_klientem
)


@inside_bp.route("/plocha")
def plocha():
    #klienti
    klienti_celkem = soucet_klientu()
  #  klient_bez_pojisteni = klienti_bez_pojisteni()
    klienti_s_pojistenim = klient_s_pojistenim()
    #pojistky
    pojistky_celkem = soucet_pojisteni()
    pojistky_bez_klienta = pojistka_bez_klienta()
    pojistky_s_klientama = pojistka_s_klientem()

    return render_template("plocha.html",
                           #klienti
                           klienti_celkem = klienti_celkem,
                          # klient_bez_pojisteni=klient_bez_pojisteni,
                           klienti_s_pojistenim=klienti_s_pojistenim,
                           #pojistky
                           pojistky_celkem = pojistky_celkem,
                           pojistky_bez_klienta = pojistky_bez_klienta,
                           pojistky_s_klientama = pojistky_s_klientama)
#------------------------------------------------------------------
@inside_bp.route("/vlozit_klienta", methods=["GET", "POST"])
def vlozit_klienta():
    return add_client()
#-------------------------------------------------------------------
@inside_bp.route("/vlozit_pojisteni", methods=["GET", "POST"])
def vlozit_pojisteni():
    return add_policy()
#------------------------------------------------------------------
@inside_bp.route("/zobrazit", methods=["GET", "POST"])
@login_required
def zobrazit():
    klienti, pojisteni = views()

    return render_template("zobrazit.html",
                           klienti=klienti,
                           pojisteni=pojisteni)
#------------------------------------------------------------------
@inside_bp.route("/seznam_klientu", methods=["GET", "POST"])
def seznam_klientu():
    klienti, pojisteni = views()
    return render_template("seznam_klientu.html",
                           klienti=klienti)
#------------------------------------------------------------------
@inside_bp.route("/seznam_pojisteni", methods=["GET", "POST"])
def seznam_pojisteni():
    klienti, pojisteni = views()
    return render_template("seznam_pojisteni.html",
                           pojisteni=pojisteni,
                           klienti=klienti)
#-------------------------------------------------------------------

app/inside/templates/plocha.html
{% extends "base.html" %}



{% block content %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 mt-3">
        <div class="card text-center">
          <div class="card-header">

            <div class="row">
              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <img class="mb-4" src="../../static/img/add.svg" alt="" width="100" height="100">
                    <h5 class="card-title">Celkem evidovaných klientů:</h5>
                    <p class="card-text card-text fs-1">{{ klienti_suma }}</p>
                    <hr>
                    <p>Počet všech klientů kteří jsou evidováni</p>
                    <a href="{{url_for('inside_bp.seznam_klientu')}}" class="btn btn-primary" role="button">Celý seznam</a>
                  </div>
                </div>
              </div>

              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <img class="mb-4" src="../../static/img/database.svg" alt="" width="100" height="100">
                    <h5 class="card-title">Celkem evidovaných pojištění</h5>
                    <p class="card-text card-text fs-1">{{ pojisteni_suma }}</p>
                    <hr>
                    <p>Počet všech pojištění která jsou evidována</p>
                    <a href="{{url_for('inside_bp.seznam_pojisteni')}}" class="btn btn-primary" role="button">Celý seznam</a>
                  </div>
                </div>
              </div>

              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <img class="mb-4" src="../../static/img/bell.svg" alt="" width="100" height="100">
                    <h5 class="card-title">Pojištěný klient</h5>
                    <p class="card-text fs-1">{{ klient_pojisteny }}</p>
                    <hr>
                    <p>Tuto kategorii obsazují pouze pojištění klienti. Tedy všichni kteří mají alespoň jedno pojištění.</p>
                    <a href="#" class="btn btn-primary">Zobrazit</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-md-12 mt-3">
        <div class="card text-center">
          <div class="card-header">

            <div class="row">
              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <img class="mb-4" src="../../static/img/pojistka_bez_klienta.svg" alt="" width="100" height="100">
                    <h5 class="card-title">Počet pojistek bez klienta:</h5>
                    <p class="card-text card-text fs-1">{{ pojistky }}</p>
                    <hr>
                    <p>Počet všech pojistek které nemají dosud žádného pojistníka</p>
                    <a href="#" class="btn btn-primary">Zobrazit</a>
                  </div>
                </div>
              </div>

              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <img class="mb-4" src="../../static/img/bookmark.svg" alt="" width="100" height="100">
                    <h5 class="card-title">Pojištěný klient</h5>
                    <p class="card-text fs-1">{{ klient_pojisteny }}</p>
                    <hr>
                    <p>Tuto kategorii obsazují pouze pojištění klienti. Tedy všichni kteří mají alespoň jedno pojištění.</p>
                    <a href="#" class="btn btn-primary">Zobrazit</a>
                  </div>
                </div>
              </div>
              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <img class="mb-4" src="../../static/img/house-check-fill.svg" alt="" width="100" height="100">
                    <h5 class="card-title">Pojištěný klient</h5>
                    <p class="card-text fs-1">{{ klient_pojisteny }}</p>
                    <hr>
                    <p>Tuto kategorii obsazují pouze pojištění klienti. Tedy všichni kteří mají alespoň jedno pojištění.</p>
                    <a href="#" class="btn btn-primary">Zobrazit</a>
                  </div>
                </div>
              </div>

            
{% endblock %}

{% block inside_content %}
{% endblock %}

app/inside/templates/seznam_klientu.html
{% extends "base.html" %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-9">

      <!--levy kontejner-->
      <div class="col-md-15 mt-3">
        <div class="card">
          <div class="card-header text-center">
            <h4>Seznam klientů</h4>
          </div>
          <div class="card-body">
            {% if klienti %}
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Jméno</th>
                    <th>Příjmení</th>
                    <th>Email</th>
                    <th>Telefon</th>
                    <th>Rok narození</th>
                    <th>Ulice</th>
                    <th>Město</th>
                    <th>PSČ</th>
                  </tr>
                </thead>
                <tbody>
                  {% for klient in klienti %}
                  <tr>
                    <td>{{ klient.first_name }}</td>
                    <td>{{ klient.last_name }}</td>
                    <td>{{ klient.email }}</td>
                    <td>{{ klient.phone_number }}</td>
                    <td>{{ klient.birth_year }}</td>
                    <td>{{ klient.street }}</td>
                    <td>{{ klient.city }}</td>
                    <td>{{ klient.postal_code }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              {% else %}
              <p>Nemáte žádné klienty.</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    
    <!--prava cast kontejneru-->
    <div class="col-md-3 mt-3">
      <div class="card">
      
        <div class="card-header text-center">
          <h4>Nápověda</h4>
        </div>
          <div class="card-body">
            <div class="accordion" id="accordionPanelsStayOpenExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                    Vytvořte pojištění
                  </button>
                
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                  <div class="accordion-body">
                    <strong>Pokud vkládáte nového pojištění</strong> vyplňte formulář a po jeho úspěšném uložení do databáze můžete klientovi nové pojištění přidat. Druhým způsobem jak vytvořit pojištěného klienta je vytvořit nejdříve pojištění a následně ho přiřadit k již vytvořenému klientovi nebo klienta následně vytvořit. Vytvořená pojištění bez klientů nebo vytvořené klienty bez pojištění najdete v rejtříku zobrazit. Pro jednoho klienta samozřejmě můžete přidat více pojištění.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    Cizinec
                  </button>
                
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                  <div class="accordion-body">
                    <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                    Věk klienta
                  
                  </button>
                </h2>
                <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                  <div class="accordion-body">
                    <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block inside_content %}
{% endblock %}

app/inside/templates/seznam_pojisteni.html
{% extends "base.html" %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-9">

      <!--levy kontejner-->
      <div class="card mt-3">
        <div class="card-header text-center">
          <h4>Seznam pojištění</h4>
        </div>
        <div class="card-body">
          {% if klienti %}
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Druh</th>
                  <th>Pojišťovna</th>
                  <th>pojistna castka</th>
                </tr>
              </thead>
              <tbody>
              {% for pojistky in pojisteni %}
                <tr>
                  <td>{{ pojistky.druh }}</td>
                  <td>{{ pojistky.pojistovna }}</td>
                  <td>{{ pojistky.pojistna_castka }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            {% else %}
            <p>Nemáte žádné pojištění.</p>
          {% endif %}
        </div>
      </div>
    </div>
    
    <!--prava cast kontejneru-->
    <div class="col-md-3 mt-3">
      <div class="card">
      
        <div class="card-header text-center">
          <h4>Nápověda</h4>
        </div>
          <div class="card-body">
            <div class="accordion" id="accordionPanelsStayOpenExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                    Vytvořte pojištění
                  </button>
                
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                  <div class="accordion-body">
                    <strong>Pokud vkládáte nového pojištění</strong> vyplňte formulář a po jeho úspěšném uložení do databáze můžete klientovi nové pojištění přidat. Druhým způsobem jak vytvořit pojištěného klienta je vytvořit nejdříve pojištění a následně ho přiřadit k již vytvořenému klientovi nebo klienta následně vytvořit. Vytvořená pojištění bez klientů nebo vytvořené klienty bez pojištění najdete v rejtříku zobrazit. Pro jednoho klienta samozřejmě můžete přidat více pojištění.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    Cizinec
                  </button>
                
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                  <div class="accordion-body">
                    <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                    Věk klienta
                  
                  </button>
                </h2>
                <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                  <div class="accordion-body">
                    <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block inside_content %}
{% endblock %}

app/inside/templates/smazat.html
{% extends "base.html" %}



{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 mt-3">
        <div class="card text-center">
          <div class="card-header">

            
            <div class="row">
              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Celkem evidencí:</h5>
                    <p class="card-text">666</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>


              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Poslední přidané pojištění</h5>
                    <p class="card-text">Podívejte se na své vytvořené evidence</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>


              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Poslední přidaný klient</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
            </div>
            <hr>
{% endblock %}

{% block inside_content %}
{% endblock %}

app/inside/templates/vlozit.html
{% extends "base.html" %}



{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 mt-3">
        <div class="card text-center">
          <div class="card-header">

            
            <div class="row">
              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Celkem evidencí:</h5>
                    <p class="card-text">666</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>


              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Poslední přidané pojištění</h5>
                    <p class="card-text">Podívejte se na své vytvořené evidence</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>


              <div class="col-sm-4 mt-3">
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title">Poslední přidaný klient</h5>
                    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
              </div>
            </div>
            <hr>
{% endblock %}

{% block inside_content %}
{% endblock %}

app/inside/templates/zobrazit.html
{% extends "base.html" %}



{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-9">

      <!--levy kontejner-->
      <div class="col-md-15 mt-3">
        <div class="card">
          <div class="card-header text-center">
            <h4>Seznam klientů</h4>
          </div>
          <div class="card-body">
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th>Jméno</th>
                  <th>Příjmení</th>
                  <th>e-mail</th>
                  <th>Telefoní číslo</th>
                  <th>Rok narození</th>
                  <th>Ulice</th>
                  <th>Město</th>
                  <th>PSČ</th>
                </tr>
              </thead>
              <tbody>
                {% for i in klienti %}
                  <tr>
                    <td>{{ i.first_name }}</td>
                    <td>{{ i.last_name }}</td>
                    <td>{{ i.email }}</td>
                    <td>{{ i.phone_number }}</td>
                    <td>{{ i.birth_year }}</td>
                    <td>{{ i.street }}</td>
                    <td>{{ i.city }}</td>
                    <td>{{ i.postal_code }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
            <a href="{{url_for('inside_bp.seznam_klientu')}}" class="btn btn-outline-secondary" role="button">Celý seznam</a>
          </div>
        </div>
      </div>
      <div class="card mt-3">
        <div class="card-header text-center">
          <h4>Seznam pojištění</h4>
        </div>
        <div class="card-body">
          <table class="table table-striped table-hover">
              <thead>
                  <tr>
                      <th>Druh</th>
                      <th>Pojišťovna</th>
                      <th>pojistna castka</th>
                  </tr>
              </thead>
              <tbody>
                  {% for i in pojisteni %}
                      <tr>
                          <td>{{ i.druh }}</td>
                          <td>{{ i.pojistovna }}</td>
                          <td>{{ i.pojistna_castka }}</td>
                      </tr>
                  {% endfor %}
              </tbody>
          </table>
          <a href="{{url_for('inside_bp.seznam_pojisteni')}}" class="btn btn-outline-secondary" role="button">Celý seznam</a>
        </div>
      </div>
    </div>
    
    <!--prava cast kontejneru-->
    <div class="col-md-3 mt-3">
      <div class="card">
      
        <div class="card-header text-center">
          <h4>Nápověda</h4>
        </div>
          <div class="card-body">
            <div class="accordion" id="accordionPanelsStayOpenExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                    Vytvořte pojištění
                  </button>
                
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                  <div class="accordion-body">
                    <strong>Pokud vkládáte nového pojištění</strong> vyplňte formulář a po jeho úspěšném uložení do databáze můžete klientovi nové pojištění přidat. Druhým způsobem jak vytvořit pojištěného klienta je vytvořit nejdříve pojištění a následně ho přiřadit k již vytvořenému klientovi nebo klienta následně vytvořit. Vytvořená pojištění bez klientů nebo vytvořené klienty bez pojištění najdete v rejtříku zobrazit. Pro jednoho klienta samozřejmě můžete přidat více pojištění.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                    Cizinec
                  </button>
                
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                  <div class="accordion-body">
                    <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="panelsStayOpen-headingThree">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                    Věk klienta
                  
                  </button>
                </h2>
                <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
                  <div class="accordion-body">
                    <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

{% block inside_content %}
{% endblock %}